-- MySQL Script generated by MySQL Workbench
-- Sat May 14 08:30:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
-- 圖書館資料庫

-- -----------------------------------------------------
-- Schema library
--
-- 圖書館資料庫
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `library` ;

-- -----------------------------------------------------
-- Table `library`.`Reader`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`Reader` (
  `ReaderNumber` INT NOT NULL AUTO_INCREMENT COMMENT '讀者編號',
  `Name` VARCHAR(45) NOT NULL COMMENT '姓名',
  `Email` VARCHAR(128) NOT NULL COMMENT '電子信箱',
  `Password` VARCHAR(128) NOT NULL COMMENT '密碼',
  PRIMARY KEY (`ReaderNumber`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`Moderator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`Moderator` (
  `Email` INT NOT NULL COMMENT '電子信箱',
  `Password` VARCHAR(128) NOT NULL COMMENT '密碼',
  PRIMARY KEY (`Email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`Book` (
  `BookNumber` INT NOT NULL AUTO_INCREMENT COMMENT '書籍編號',
  `Title` VARCHAR(256) NOT NULL COMMENT '名稱',
  `Author` VARCHAR(256) NULL COMMENT '作者',
  `Publisher` VARCHAR(256) NULL COMMENT '出版商',
  PRIMARY KEY (`BookNumber`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`Copy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`Copy` (
  `CopyNumber` INT NOT NULL AUTO_INCREMENT COMMENT '書籍副本編號',
  `BookNumber` INT NOT NULL COMMENT '書籍編號',
  `SequenceNumber` INT NULL COMMENT 'ISBN',
  `Type` TINYINT(1) NOT NULL COMMENT '書籍副本狀態',
  `Price` INT NULL COMMENT '價格',
  INDEX `BookNumber_idx` (`BookNumber` ASC) VISIBLE,
  CONSTRAINT `BookNumber`
    FOREIGN KEY (`BookNumber`)
    REFERENCES `library`.`Book` (`BookNumber`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`CirculatedCopy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`CirculatedCopy` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '編號',
  `ReaderNumber` INT NULL COMMENT '讀者編號',
  `CopyNumber` INT NULL COMMENT '書籍副本編號',
  `BorrowDate` DATETIME NOT NULL COMMENT '借閱時間',
  `DueDate` DATETIME NULL COMMENT '借閱期限',
  `ReturnDate` DATETIME NULL COMMENT '歸還時間',
  `FineAmount` INT NULL COMMENT '罰款金額',
  PRIMARY KEY (`ID`),
  INDEX `ReaderNumber_idx` (`ReaderNumber` ASC) VISIBLE,
  INDEX `CopyNumber_idx` (`CopyNumber` ASC) VISIBLE,
  CONSTRAINT `ReaderNumber`
    FOREIGN KEY (`ReaderNumber`)
    REFERENCES `library`.`Reader` (`ReaderNumber`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `CopyNumber`
    FOREIGN KEY (`CopyNumber`)
    REFERENCES `library`.`Copy` (`CopyNumber`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`Reserved`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`Reserved` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '編號',
  `ReaderNumber` INT NULL COMMENT '讀者編號',
  `BookNumber` INT NULL COMMENT '書籍編號',
  `Date` DATETIME NULL COMMENT '預借日期',
  `Status` TINYINT(1) NULL COMMENT '預借狀態',
  PRIMARY KEY (`ID`),
  INDEX `BookNumber_idx` (`BookNumber` ASC) VISIBLE,
  CONSTRAINT `ReaderNumber`
    FOREIGN KEY ()
    REFERENCES `library`.`Reader` ()
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `BookNumber`
    FOREIGN KEY (`BookNumber`)
    REFERENCES `library`.`Book` (`BookNumber`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
